### ISSUE TITLE
Streamer token and url not working from /api-quote-tokens

### ISSUE THREAD

**Issue by avramescur** [tastytrade/tastytrade-api-js#9]
I found out that getting the wss URL and the token for DXlink is not working with the information obtained from endpoint /api-quote-tokens. In the Tasty Trade Postman collection I found there is another endpoint which allows to obtain dxlink token as well as a different wss URL and those are working. Endpoint is /quote-streamer-tokens

Can someone look into this? Change is needed here: https://github.com/tastytrade/tastytrade-api-js/blob/a495ca0e20744acfe29c9855a442fe320fe99f15/lib/services/accounts-and-customers-service.ts#L31

**Comment by dmoss18** [comment]
@avramescur Due to licensing concerns, the DxLink token returned from `GET /api-streamer-tokens` only provides Nasdaq basic equities. API users shouldn't be using the `/quote-streamer-tokens` endpoint to get a DxLink token as this violates our licensing terms. Sorry for the trouble. We are working on getting the licensing concerns worked out.

For the time being, please only use the `/api-streamer-tokens` endpoint. API users who rely on the `/quote-streamer-tokens` endpoint will be flagged and put on delayed quotes.
